### ISSUE TITLE
Flutter iOS setUserData

### ISSUE THREAD

**Issue by polivmi1** [Countly/countly-sdk-flutter-bridge#1]
On iOS I am experiencing an issue. Initialization is fine, but then when setting userData it will throw an exception.
Android seems to catch the exception without properly setting user data.

`Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSNull integerValue]: unrecognized selector sent to instance 0x7fff80618070'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff23c7127e __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00007fff513fbb20 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff23c91fd4 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x00007fff23c75c4c ___forwarding___ + 1436
	4   CoreFoundation                      0x00007fff23c77f78 _CF_forwarding_prep_0 + 120
	5   countly_flutter                     0x000000010d88cc03 -[CountlyFlutterPlugin handleMethodCall:result:] + 3811
	6   Flutter                             0x000000010b77e141 __45-[FlutterMethodChannel setMethodCallHandler:]_block_invoke + 104
	7   Flutter                             0x000000010b70e27e _ZNK7flutter21PlatformMessageRouter21HandlePlatformMessageEN3fml6RefPtrINS_15PlatformMessageEEE + 166
	8   Flutter                             0x000000010b711d74 _ZN7flutter15PlatformViewIOS21HandlePlatformMessageEN3fml6RefPtrINS_15PlatformMessageEEE + 38
	9   Flutter                             0x000000010b7782d3 _ZNSt3__110__function6__funcIZN7flutter5Shell29OnEngineHandlePlatformMessageEN3fml6RefPtrINS2_15PlatformMessageEEEE4$_32NS_9allocatorIS8_EEFvvEEclEv + 57
	10  Flutter                             0x000000010b7223db _ZN3fml15MessageLoopImpl10FlushTasksENS_9FlushTypeE + 117
	11  Flutter                             0x000000010b726b46 _ZN3fml17MessageLoopDarwin11OnTimerFireEP16__CFRunLoopTimerPS0_ + 26
	12  CoreFoundation                      0x00007fff23bd4b94 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 20
	13  CoreFoundation                      0x00007fff23bd4882 __CFRunLoopDoTimer + 1026
	14  CoreFoundation                      0x00007fff23bd3eda __CFRunLoopDoTimers + 266
	15  CoreFoundation                      0x00007fff23bcec4e __CFRunLoopRun + 2238
	16  CoreFoundation                      0x00007fff23bce066 CFRunLoopRunSpecific + 438
	17  GraphicsServices                    0x00007fff384c0bb0 GSEventRunModal + 65
	18  UIKitCore                           0x00007fff48092d4d UIApplicationMain + 1621
	19  Runner                              0x000000010a493f58 main + 72
	20  libdyld.dylib                       0x00007fff5227ec25 start + 1`

**Comment by nicolsondsouza** [comment]
Ok, will fix it.

**Comment by nicolsondsouza** [comment]
Can you post your same data you are trying to send

**Comment by polivmi1** [comment]
`
    Map<String, Object> options = {
      "name": data.name,
      "phone": data.phone,
      "email": data.email,
      "isReadOnly": data.isReadOnly,
      "type": data.type,
      "organization": data.organization,
    };
    Countly.setUserData(options);`

All Strings, but isReadOnly, which is boolean

**Comment by trinisofttechnologies** [comment]
Ok

**Comment by trinisofttechnologies** [comment]
isReadyOnly is not a valid type.

Please look at the docs for valid type.

You can use setProperty method for additional values.

**Comment by trinisofttechnologies** [comment]
https://support.count.ly/hc/en-us/articles/360037944212-Flutter#modifying-custom-data

**Comment by polivmi1** [comment]
I see. I didn't know setUserData has to use only mentioned Strings as it is a map of <String,Object>. Would it make sense to have it as an enum such as Map<UserProperty, Object>?

**Comment by trinisofttechnologies** [comment]
I will check if these are the only values to be set.

But I mostly assume yes.

You can use setProperty for custom data.

**Comment by trinisofttechnologies** [comment]
byear default value missing added and pushed.

**Comment by polivmi1** [comment]
Works well. Thank you
