### ISSUE TITLE
How can we use disableLocation in Flutter code

### ISSUE THREAD

**Issue by a-href** [Countly/countly-sdk-flutter-bridge#116]
It seems that disableLocation doesn't avaiable at Flutter framework, so how can we use disableLocation in Flutter code if we don't want Countly systematically collect user locations, such as the following data:
<img width="770" alt="image" src="https://github.com/Countly/countly-sdk-flutter-bridge/assets/13159272/f88aaabf-3806-48f6-9995-550f259ebf19">

How can we disable this data and clear it in flutter code

**Comment by ArtursKadikis** [comment]
Hello, our SDK's don't collect location information automatically. It would be up to the integrator to provide this information.
The server side does perform revers geo-ip lookup and approximates the closest country and city (if possible) from the IP. To prevent this automatic lookup, you would call the following after initializing the SDK:
https://support.count.ly/hc/en-us/articles/360037944212-Flutter#disable-location

**Comment by a-href** [comment]
@ArtursKadikis  but the disableLocation function does't avaible at Flutter SDK, it only implement at native code

**Comment by a-href** [comment]
@ArtursKadikis  How to prohibit the server side revers geo-ip lookup?

**Comment by ArtursKadikis** [comment]
Hello, looks like the documentation was mentioning a call that does not exist currently.

You can also disable it form your "app settings" in your caountly dashboard:
![image](https://github.com/Countly/countly-sdk-flutter-bridge/assets/10658133/19bbf59d-0622-4fd9-a4b6-cf9bcf1c1e2e)

**Comment by ArtursKadikis** [comment]
Those settings should disable future computation of revers geo-ip. It will not delete historical data.
On way to delete it would be to require consent in the SDK and not give the location consent.

**Comment by a-href** [comment]
> Those settings should disable future computation of revers geo-ip. It will not delete historical data. On way to delete it would be to require consent in the SDK and not give the location consent.

Hi @ArtursKadikis , unfortunately, the new data still have the loc data after I remove the location consent and turned off `Track country data` and `Track city data`, but still thanks for your kindly help .

**Comment by ArtursKadikis** [comment]
could you possibly share you SDK init code?

**Comment by a-href** [comment]
> could you possibly share you SDK init code?

Yes, as follows:

```
  Countly.isInitialized().then((isInitialized) async {
      if (!isInitialized) {
        CountlyConfig config = CountlyConfig(serverUrl, appKey)
          ..enableCrashReporting()
          ..setEventQueueSizeToSend(100)
          ..enableCrashReporting()
          ..setUserProperties(await _getInitlizaUserProperties())
          ..setLoggingEnabled(enableLogging);
        logMessage("Countly: Initializing...");
        await Future.wait([
          Countly.initWithConfig(config).then(
            (value) {
              Countly.appLoadingFinished();
              _reclaimFlutterErrorHandler();
              startSession();
              logMessage("Countly: Finished initialization");
            },
          ),
        ]).timeout(
          const Duration(seconds: 5),
          onTimeout: () async {
            logError(
              "Countly: Timeout while sending configuration. Countly may launch with default values.",
            );
            return [];
          },
        ).catchError((error) async {
          logError("Countly: Error while initWithConfig");
          return <Null>[];
        });
        Countly.removeConsent(["location"]);
      }
    });
```

**Comment by ArtursKadikis** [comment]
I think I see the problem. You have not enabled the consent feature during init.
You would need to add the following:
`config.setRequiresConsent(true)`
More info here:
https://support.count.ly/hc/en-us/articles/360037944212-Flutter#setup-during-init

For everything else to function as before, you would also need to give consent for all other features during init.

**Comment by a-href** [comment]
As following data showed, the consent of location is false, but the loc data has still been created.

```
  {
  "_id": “xxx”,
  "uid": “xx”,
  "did": “xxx”,
  "first_req_get": “xxxx”,
  "first_req_post": "",
  "av": "xxx",
  "cc": "Unknown",
  "cty": "Unknown",
  "custom": {
  },
  "d": "x86_64",
  "data": {},
  "dt": "mobile",
  "engagement": {
    "2023-07-06": {
      "sc": 1,
      "sd": xxxx
    }
  },
  "engagement_score": 0,
  "fac": 1688631360,
  "first_sync": 1688631360,
  "fs": 1688631360,
  "fsd": "20230706",
  "fsm": "202307",
  "fsw": "20230703",
  "hasInfo": true,
  "ingested": false,
  "lac": xxx,
  "last_req": “xxx”,
  "last_req_get": “”xxxx
  "last_sync": xxx,
  "lbst": xxx,
  "loc": {
    "gps": false,
    "geo": {
      "type": "Point",
      "coordinates": [
        121.4581,
        31.2222
      ]
    },
    "date": 1688631360263
  },
  "ls": xxx,
  "lsid": “xxxx”,
  "lv": “xxxxx”,
  "lvt": 1688633010,
  "merged_did": “xxxxxx”,
  "merged_uid": “x”,
  "merges": x,
  "mnf": "Apple",
  "p": "iOS",
  "pv": "i16:4",
  "r": "1179x2556",
  "req_count": xx,
  "rgn": "SH",
  "sc": 1,
  "sd": 0,
  "sdk": {
    "name": "dart-flutterbnp-ios",
    "version": "23.6.0"
  },
  "t": "0",
  "tsd": 1650,
  "tz": "480",
  "vc": 0,
  "lest": 1688633010,
  "hadAnyFatalCrash": 1688633010,
  "hadAnyNonfatalCrash": 1688633010,
  "consent": {
    "apm": false,
    "attribution": false,
    "crashes": false,
    "events": false,
    "feedback": false,
    "location": false,
    "push": false,
    "remote-config": false,
    "sessions": false,
    "users": false,
    "views": false
  }
}
```

**Comment by ArtursKadikis** [comment]
Could you have a look at the "incomming request log" and check if there has been a request that sends the location param with an empty string? Something like: ' &location="" '
