### ISSUE TITLE
getRemoteConfigValueForKey returns "0"/"1" for false/true

### ISSUE THREAD

**Issue by mars3142** [Countly/countly-sdk-flutter-bridge#142]
Why is the value in remote config converted? I want the raw value. If the value would be false/true (as boolean) instead of 0/1 (as string), it would be fine, but not the current implementation.

**Comment by turtledreams** [comment]
Hi, thank you for reaching out. This is a known issue and that function is deprecated and replaced with getValue() method (https://support.count.ly/hc/en-us/articles/360037944212-Flutter#h_01HD1KX616GDFGTV2AR8BSWWG9) at version 23.6.0 (https://github.com/Countly/countly-sdk-flutter-bridge/releases).

**Comment by mars3142** [comment]
How long will deprecated functions in the SDK? 

It's not annotated as deprecated within the SDK, which is bad. Because of this, I didn't know about the deprecation.

**Comment by turtledreams** [comment]
Deprecated calls usually stay for 1 to 1.5 years till we remove them.
