### ISSUE TITLE
stack trace don`t show properly

### ISSUE THREAD

**Issue by amir1430** [Countly/countly-sdk-flutter-bridge#191]
![image](https://github.com/Countly/countly-sdk-flutter-bridge/assets/46561556/5e461cab-2e48-40be-b0da-4fd146117bbe)
there is no stacktrace but in data log
![Screenshot 2024-01-13 183113](https://github.com/Countly/countly-sdk-flutter-bridge/assets/46561556/a5515919-baab-4d61-8043-ebc58acda31a)
and in flutter this is the code to send log
```dart
  await Countly.logExceptionEx(
    exception,
    true,
    stacktrace: stackTrace,
    segmentation: {
      'stacktrace': '$stackTrace',
      'user_id': userId != null ? '$userId' : 'anonymous',
      if (segment != null) 'segment': segment,
      if (moreInfo != null) ...moreInfo,
    },
  );
```

**Comment by amir1430** [comment]
Hi 
thanks you for your quick response.

**Comment by amir1430** [comment]
any update?

**Comment by turtledreams** [comment]
Hi @amir1430. This is still under development and will possibly be at the next minor release of the server (around a month or so).

**Comment by turtledreams** [comment]
Hi @amir1430 , this issue must be solved with the latest server and SDK releases. Let us know if you experience a problem. Cheers.
