### ISSUE TITLE
Countly.logException "nonFatal" argument name

### ISSUE THREAD

**Issue by sbatezat** [Countly/countly-sdk-flutter-bridge#205]
The method signature of *logExceptionEx*, *logExceptionManual* and *logException* (the one called by the two previous ones) contains a parameter named "nonFatal".

`  static Future<String?> logException(String exception, bool nonfatal, [Map<String, Object>? segmentation]) async {
`

However, on the [Android implementation](https://github.com/Countly/countly-sdk-flutter-bridge/blob/8d396ed2889d5e1793e89eeb3625ae664545331a/android/src/main/java/ly/count/dart/countly_flutter/CountlyFlutterPlugin.java#L393) (probably on other implementations too, didn't had time to double check), the argument is parsed as "fatal" and use as if it was a fatal argument sent.
                
`boolean fatal = args.getBoolean(1);`

**Expected :** 

The argument on all 3 logException functions should be named "fatal".

**Comment by peterBrxwn** [comment]
Hello,
Thank you for bringing this to our attention.
We have begun working on it.
