### ISSUE TITLE
Neverending call for Countly.reportFeedbackWidgetManually on iOS

### ISSUE THREAD

**Issue by sbatezat** [Countly/countly-sdk-flutter-bridge#206]
I'm using that API on an async function:

```
await Countly.reportFeedbackWidgetManually(
    widgetInfo,
    widgetData,
    {
      "rating": rating,
      "comment": comment,
      "email": email,
      "contactMe": true,
    },
  );
```

It's neverending, the future is never resolved, only on iOS. Indeed, on Android, the future is resolved.

**Comment by peterBrxwn** [comment]
Hi there,
Thanks for flagging this.
We've replicated the bug and I've made a pull request to address it. [PR](https://github.com/Countly/countly-sdk-flutter-bridge/pull/208)

We'll include the fix in the next release.

**Comment by sbatezat** [comment]
Is it included on latest releases? It seems to be (nut I haven't tested it).
If so, issue should be closed

**Comment by peterBrxwn** [comment]
Yes, it was included in the latest release.

Closing this issue.
