### ISSUE TITLE
Error: MissingPluginException(No implementation found for method isInitialized on channel countly_flutter)

### ISSUE THREAD

**Issue by remohammadi** [Countly/countly-sdk-flutter-bridge#223]
I receive this error when I run my app on Chrome. The same code works well on Android, and I can see data being sent successfully there.

I have tried `flutter clean` but it didn't help.

Complete stacktrace:
```
Error: MissingPluginException(No implementation found for method isInitialized on channel countly_flutter)
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 297:3  throw_
packages/flutter/src/services/platform_channel.dart 332:7                    _invokeMethod
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50           <fn>
dart-sdk/lib/async/zone.dart 1661:54                                         runUnary
dart-sdk/lib/async/future_impl.dart 162:18                                   handleValue
dart-sdk/lib/async/future_impl.dart 838:44                                   handleValueCallback
dart-sdk/lib/async/future_impl.dart 867:13                                   _propagateToListeners
dart-sdk/lib/async/future_impl.dart 643:5                                    [_completeWithValue]
dart-sdk/lib/async/future_impl.dart 713:7                                    callback
dart-sdk/lib/async/schedule_microtask.dart 40:11                             _microtaskLoop
dart-sdk/lib/async/schedule_microtask.dart 49:5                              _startMicrotaskLoop
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 181:7           <fn>
```

**Comment by peterBrxwn** [comment]
Hello @remohammadi,

Please note that the Countly Flutter SDK only supports the **Android** and **iOS** platforms, as outlined [here](https://github.com/Countly/countly-sdk-flutter-bridge/blob/32fd7f93d1c7617ba2305aa24b52f0e3a929a421/pubspec.yaml#L8-L10).

**Web platform is not supported.**
Thank you.

**Comment by remohammadi** [comment]
Oh! From [the description here](https://pub.dev/packages/countly_flutter) I felt that web is supported.

Is there a serious blocker for supporting web, or it is not supported because it has not been prioritized? If the second one, do you accept pull requests to add support for Web platform?

Thanks.

**Comment by peterBrxwn** [comment]
The description refers to **Countly**, our analytics solution, which supports web, mobile, and desktop applications through various SDKs.
Not this SDK.

To support all Flutter platforms (including web), we want to write the entire SDK in pure Dart. However, this undertaking is quite significant in scope and complexity.
Once we initiate this development effort, we’ll certainly be open to receiving pull requests.

Thank you.
