### ISSUE TITLE
Access denied finding property "ro.vendor.audio.cloudctrl"

### ISSUE THREAD

**Issue by sanjaysharmajw** [Countly/countly-sdk-flutter-bridge#227]
Access denied finding property "ro.vendor.audio.cloudctrl"

**Comment by peterBrxwn** [comment]
Hello @sanjaysharmajw,
Thank you for bringing this to attention.

Could you kindly provide a more detailed description of the error (including full logs)?
Additionally, it would be helpful to know what actions you were performing just before the error occurred.
Oh, and could you double-check that the error is related to the Countly Flutter SDK?

Looking forward to your response so we can tackle this issue together!
