### ISSUE TITLE
SDK does not set APP key

### ISSUE THREAD

**Issue by danielfoehrKn** [Countly/countly-sdk-flutter-bridge#27]
Hi,

I am self-hosting the community server of Countly.
I am able to reach the backend server via API and get an http 200 response code back (the app key and device ID is not real in this example).

```
curl -v https://countly.mediathekviewmobile.de:32443/i?app_key=123456789&device_id=<MY_ID>&timestamp=1610823756437&hour=20&dow=6&tz=60&sdk_version=20.04.2&sdk_name=dart-flutterb-ios&consent=%7B%22location%22%3Atrue%7D
```

However, the mobile App is sending the wrong requests. Captured from my L7 LoadBalancer

```
GET /i?app_key=YOUR_API_KEY&device_id=<ID>&timestamp=1610823756437&hour=20&dow=6&tz=60&sdk_version=20.04.2&sdk_name=dart-flutterb-ios&consent=%7B%22location%22%3Atrue%7D HTTP/2.0" 400 31 "-" "MediathekView/1 CFNetwork/1206 Darwin/20.1.0" 239 0.003 [default-countly-api-3001] [] 10.108.0.12:3001 42 0.002 400 b9f6c20b147e19662aba25a390348894
```

Observe that for the app_key it uses some default value **YOUR_API_KEY** - this causes the request to fail.
However, I do set the APP_KEY explicitly in the dart code during application startup.

```
Countly.init("https://countly.mediathekviewmobile.de:32443", "my-app-key").then((value) {
            logger.info("COUNTLY STARTED");
            Countly.start();
          });
```

This happens when running the flutter app on iOS.
Any help is appreciated! Thanks.

**Comment by ijunaid** [comment]
Hi @danielfoehrKn,

We have implemented a queue in which requests are added before sending them to the server, after successfully sending the request to the server we will remove that request from the queue.
In your above-mentioned case, it looks like that there is a request with the wrong app_key is cached in the queue, uninstall and reinstall the app will fix this issue.

**Comment by danielfoehrKn** [comment]
Thanks for your response.
So you are saying that the SDK indefinitely tries to send the first request in the queue - but this always fails because it was initially enqueued with a default APP_KEY?
Is that queue persisted on the filesystem, so I could also just remove the app data?

**Comment by ijunaid** [comment]
Leaving it in the queue even with a failed request is such by design. There can sometimes be circumstances where a valid request fails to send its data (server issue, wrong firewall config, etc).

The request won't be stuck in the queue forever. Request queue has a maximum size of 1000 requests. When that fills up, the oldest requests get removed.

Yes, just removing the app data also fix this issue.

**Comment by danielfoehrKn** [comment]
Thanks, after deleting the app data it worked.
