### ISSUE TITLE
Intent redirection issue on NotificationBroadcastReceiver

### ISSUE THREAD

**Issue by Michael12jan** [Countly/countly-sdk-flutter-bridge#32]
Hi,

My application fails submission to the google play due to intent redirection, upon further request they provided with additional details:

> Google play app submission violated the Device and Network Abuse policy as it contained an Intent Redirection issue in class: 
> ly.count.android.sdk.messaging.CountlyPush$NotificationBroadcastReceiver.onReceive.

We managed to get our app approved after we disable the notification, but we need the notification function from Countly. Any help on how to rectify this issue so that we can use Countly notification will be greatly appreciated.

Below is the Countly initialization code:

```
    Countly.isInitialized().then((bool isInitialized) {
      if (!isInitialized) {
        Countly.setLoggingEnabled(true);
        Countly.enableCrashReporting();
        Countly.setRequiresConsent(true);
        Countly.setHttpPostForced(true);
        Countly.start();
        Countly.init("https://asia-try.count.ly", Env.url.COUNTLY_APIKEY)
            .then((value) {
          Countly.start();
          Countly.giveAllConsent();
        });
      } else {
        print('Countly: Already initialized.');
      }
    });
```

**Comment by ArtursKadikis** [comment]
Which SDK version were you using?

**Comment by Michael12jan** [comment]
We are using 20.04.2 now

**Comment by ArtursKadikis** [comment]
Could you try it with 20.11.1? That issue should be fixed there.

**Comment by Michael12jan** [comment]
Ok, we will try to update the version and try to submit to the store again, will update here once we get any news from Google. Thank you for the help!

**Comment by Michael12jan** [comment]
Hi,
We managed to get our app approved with notification enables once we update the Countly. Thank you very much!
