### ISSUE TITLE
Countly Flutter SDK Performance monitoring Screen trace

### ISSUE THREAD

**Issue by Michael12jan** [Countly/countly-sdk-flutter-bridge#48]
Hi! 
I implemented Countly-sdk-flutter on my flutter application and enabled the Application performance monitoring, but for some reason in the Countly dashboard Application performance Screen trace is not showing any data. Is there a way to check if there is any reason on why it's happening? 

Countly version: 20.11.3
Flutter version: 2.2.3

**Comment by ArtursKadikis** [comment]
Hello, the Flutter SDK currently does not collect Screen traces.

**Comment by Michael12jan** [comment]
Noted, thanks for the clarification.
