### ISSUE TITLE
wrong isInitialized state after hot restart

### ISSUE THREAD

**Issue by mars3142** [Countly/countly-sdk-flutter-bridge#89]
We check with ```await Countly.isInitialized()``` the state and it returned true, because it does a native call.  See https://github.com/Countly/countly-sdk-flutter-bridge/blob/master/lib/countly_flutter.dart#L175

After that we want to use any Countly method, but this is checking the private member variable ```_isInitialized```, which is still false. So no Countly call will be used after hot restart. 

I would always call ```await Countly.isInitialized()```, which will return true, if ```_isInitialized``` is true or do a native call and set the private member depending on the result.

**Comment by ijunaid** [comment]
@mars3142 
Thanks for reporting this issue
We have fixed it in release **22.09.0**
https://github.com/Countly/countly-sdk-flutter-bridge/releases/tag/22.9.0-np
